language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python src/main.py -t +10:00 -a 2017-05-16 -b 2017-05-17 -i realDonaldTrump
  - python -m unittest discover tests
notifications:
  email: false
